# Version format
version: 1.0.{build}

# Branches to build
branches:
  only:
  - master

# Start builds on tags only
#skip_non_tags: true

# Skipping commits
skip_commits:
  files:
    - README.md

# Maximum number of concurrent jobs for the project
max_jobs: 1

# Fetch repository as zip archive
shallow_clone: true

# Clone directory
clone_folder: c:\projects\pasdivert

# Scripts that run after cloning repository
install:
- cmd: scripts\install-lazarus.cmd

cache:
- c:\lazarus -> scripts\install-lazarus.cmd

# Build scripts
build_script:
- cmd: scripts\build.cmd

artifacts:
- path: fpc\Win32\Release\*.exe
  name: pasdivert-win32
  type: WebDeployPackage
- path: fpc\Win64\Release\*.exe
  name: pasdivert-win64
  type: WebDeployPackage

#deploy: off
